apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcoya-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcoya-app
  template:
    metadata:
      labels:
        app: dcoya-app
    spec:
      containers:
      - name: dcoya-app
        image: tomer60300/dcoya-app:1.0.1
        ports:
        - containerPort: 443
        env:
          - name: MACHINE_NAME
            value: "tomer-machine"

---

apiVersion: v1
kind: Service
metadata:
  name: dcoya-app-service
spec:
  selector:
    app: dcoya-app
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
